version: '3'

services:
  payment-gateway-mock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: "dev-secret-key"
    restart: unless-stopped
    container_name: payment-gateway-mock